server {
    listen 80;

    location / {
        proxy_pass http://secure-platform:3000;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        add_header X-Frame-Options "DENY";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";
    }
}
